name: meiliadmin

services:
  meili:
    image: getmeili/meilisearch:v1.8
    ports:
      - 7700:7700
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: masterkey
    volumes:
      - meili_data:/meili_data

volumes:
  meili_data:
